import { ArrowUpRight, Radio, Terminal } from 'lucide-react';
import { MotionLayer } from './motion-layer';

const projects = [
  { number: '01', title: 'MeetStream Labs', eyebrow: 'OPEN SOURCE · DEVELOPER EXPERIENCE', text: 'Runnable examples for building meeting bots and AI agents across Zoom, Google Meet, and Microsoft Teams.', stack: 'webhooks / real-time media / Node.js', href: 'https://github.com/meetstream-ai/labs', signal: 'MEET / STREAM / SHIP' },
  { number: '02', title: 'MIA Chat Agent', eyebrow: 'MEETSTREAM · AGENT WORKFLOW', text: 'A meeting chat agent that listens for a wake phrase, routes a request through a hosted agent, and posts the answer back into the call.', stack: 'webhooks / ngrok / Node.js', href: 'https://github.com/meetstream-ai/labs/tree/main/MIA-chat-agent', signal: 'WAKE → ROUTE → ANSWER' },
  { number: '03', title: 'Interview Copilot', eyebrow: 'PERSONAL BUILD · AI PRODUCT', text: 'An experiment in turning high-pressure interview moments into useful, context-aware feedback.', stack: 'TypeScript / AI workflows / product thinking', href: 'https://github.com/Arjun220905', signal: 'LISTEN / THINK / IMPROVE' },
];

export default function Home() {
  return <main>
    <MotionLayer />
    <div className="scroll-progress" aria-hidden="true" />
    <nav className="nav shell" aria-label="Primary navigation"><a className="wordmark" href="#top" aria-label="Arjun M home"><span>A</span><i>Arjun M</i></a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="#notes">Notes</a></div><a className="nav-cta" href="https://www.linkedin.com/in/arjun-m-39b317290/" target="_blank" rel="noreferrer">Let&apos;s talk <ArrowUpRight size={15} /></a></nav>
    <section id="top" className="hero shell"><div className="hero-kicker"><span className="pulse" /> DEVELOPER RELATIONS × BACKEND SYSTEMS</div><h1>The API working<br /><em>is only half the job.</em></h1><div className="hero-bottom"><p>I build and explain practical infrastructure so developers can go from <strong>“interesting”</strong> to <strong>“shipped.”</strong></p><a className="text-link" href="#work">See the work <ArrowUpRight size={16} /></a></div><div className="hero-orb" aria-hidden="true" /><div className="hero-grid" aria-hidden="true">{Array.from({length:8},(_,i)=><span key={i} />)}</div></section>
    <section id="work" className="work section shell"><div className="section-label"><span>01</span><span>SELECTED WORK</span><span className="line" /></div><div className="section-intro"><h2>Building the bridge<br /><em>between systems and people.</em></h2><p>Backend logic, AI workflows, and the developer experience around them.</p></div><div className="project-list">{projects.map((project)=><article className="project" key={project.number}><div className="project-index">{project.number}</div><div className="project-copy"><div className="eyebrow">{project.eyebrow}</div><h3>{project.title}</h3><p>{project.text}</p><div className="project-meta"><span>{project.stack}</span><a href={project.href} target="_blank" rel="noreferrer">View source <ArrowUpRight size={14} /></a></div></div><div className="project-signal"><Radio size={16} /><span>{project.signal}</span><div className="signal-bars"><i /><i /><i /><i /><i /></div></div></article>)}</div></section>
    <section className="signal-strip shell" aria-label="What I work across"><div><span>01</span><strong>APIs / WEBHOOKS</strong><small>Make the complicated usable.</small></div><div><span>02</span><strong>REAL-TIME MEDIA</strong><small>Meetings, agents, useful moments.</small></div><div><span>03</span><strong>BUILD / WRITE / EXPLAIN</strong><small>The loop behind the work.</small></div></section>
    <section id="about" className="about section shell"><div className="section-label"><span>02</span><span>THE THROUGH-LINE</span><span className="line" /></div><div className="about-grid"><h2>Make unfamiliar work<br /><em>feel obvious.</em></h2><div className="about-copy"><p>I&apos;m Arjun, a Computer Science student and Developer Relations &amp; Go-to-Market intern at <a href="https://meetstream.ai" target="_blank" rel="noreferrer">MeetStream</a>.</p><p>I work where backend engineering, developer experience, technical content, and go-to-market meet. I care about the gap between “the API works” and “a developer can ship with it.”</p><p className="off-hours">Outside the build: movies, music, puzzles, and figuring out how things work.</p><div className="principles"><div><span>01</span><strong>Runnable beats theoretical.</strong></div><div><span>02</span><strong>Clarity is a product feature.</strong></div><div><span>03</span><strong>Good defaults earn trust.</strong></div></div></div></div></section>
    <section id="notes" className="notes section shell"><div className="section-label"><span>03</span><span>NOW / NOTES</span><span className="line" /></div><div className="notes-grid"><div><div className="now-tag"><span className="pulse" /> CURRENTLY EXPLORING</div><h2>Meeting agents,<br /><em>developer adoption.</em></h2></div><div className="note-card"><Terminal size={17} /><p>Writing about APIs, webhooks, real-time media, and the tiny decisions that make infrastructure easier to adopt.</p><div className="article-links"><a href="https://meetstream.ai/blog/how-to-build-an-ai-meeting-agent-that-generates-designs-on-command-and-shares-them-in-chat-2/" target="_blank" rel="noreferrer"><span>01</span>AI meeting agents that take action <ArrowUpRight size={14} /></a><a href="https://meetstream.ai/blog/how-to-build-a-live-meeting-chat-agent/" target="_blank" rel="noreferrer"><span>02</span>Live meeting chat agents <ArrowUpRight size={14} /></a><a href="https://meetstream.ai/blog/how-to-record-each-participant-separately-in-a-video-call/" target="_blank" rel="noreferrer"><span>03</span>Per-participant recording <ArrowUpRight size={14} /></a><a href="https://meetstream.ai/blog/how-to-build-a-post-call-transcription-bot-with-meetstream/" target="_blank" rel="noreferrer"><span>04</span>Post-call transcription bots <ArrowUpRight size={14} /></a></div><a className="text-link" href="https://meetstream.ai/blog/author/arjun/" target="_blank" rel="noreferrer">View all writing <ArrowUpRight size={16} /></a></div></div></section>
    <footer className="footer shell"><div><div className="footer-kicker">HAVE A GOOD PROBLEM?</div><h2>Let&apos;s make it<br /><em>shippable.</em></h2></div><div className="footer-right"><a href="https://www.linkedin.com/in/arjun-m-39b317290/" target="_blank" rel="noreferrer" className="email-link">Connect on LinkedIn <ArrowUpRight size={17} /></a><div className="socials"><a href="https://github.com/Arjun220905" target="_blank" rel="noreferrer" aria-label="GitHub">GH</a><a href="https://www.linkedin.com/in/arjun-m-39b317290/" target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href="https://x.com/arjunnn2209" target="_blank" rel="noreferrer" aria-label="X">𝕏</a></div><small>© 2026 ARJUN M / BUILT WITH INTENT</small></div></footer>
  </main>;
}
